[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[context.production.environment]
  NODE_ENV = "production"
  HUGO_ENV = "production"
  HUGO_VERSION = "0.130.0"
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"



[dev]
  functions = "functions"
